parameters:
#    ecommerce_user.example.class: Ecommerce\Bundle\UserBundle\Example

services:
#    ecommerce_user.example:
#        class: %ecommerce_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
